#define USERS_FILENAME "reg_users.data"
#define USERS_TEMP_FILENAME "reg_users_temp.data"
#define ITEMS_FILENAME "items_stock.data"
#define ITEMS_TEMP_FILENAME "items_stock_temp.data"
#define DATA_FOLDERNAME "labc_sm_data"
#define FILE_DELIM "[#]"
#define BUYLIST_DELIM ";"
#define TEXT_WRITE_SPEED 7.0

#define COLOR_RED     "\x1b[31m"
#define COLOR_GREEN   "\x1b[32m"
#define COLOR_YELLOW  "\x1b[33m"
#define COLOR_BLUE    "\x1b[34m"
#define COLOR_MAGENTA "\x1b[35m"
#define COLOR_CYAN    "\x1b[36m"
#define COLOR_RESET   "\x1b[0m"
